name: Prettier Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  prettier_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - name: Install depenencies
        run: yarn --frozen-lockfile

      - name: Run prettier check
        run: yarn fmt:check
